spring:
  datasource:
    url: ENC(rjJUIny4VSkn1pwLejDvdHwhGGAj7NWdi/qf2a1tygrCZtFfqTQjwKTe6QvDOZNAPm/jD/Qi7KV26Csnlg69DAny4SMbQLVU)
    username: ENC(VloDGe/gytKO2ciTa/GY8A==)
    password: ENC(hQt4eNpbvbOQPRdQJnGG3qErkd4D+lT3)
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database: mysql
  sql:
    init:
      continue-on-error: true